version: '3'
services:
  app:
    build: ./app
    container_name: vote_app
    restart: always
    tty: true
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    depends_on:
      - db
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
      - ./app/static/:/usr/src/app/static
    env_file:
      - ./envs/db.env
      - ./envs/app.env
      - .env
    networks:
      app_net:
        ipv4_address: 192.168.1.2
      # - django_vote

  nginx:
    image: nginx
    container_name: vote_nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/mime.types:/etc/nginx/mime.types"
      - "./app/static:/usr/src/app/static"
    depends_on:
      - app
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: 192.168.1.3
      # - django_vote

  db:
    build: ./mysql
    container_name: vote_db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data_dir:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./envs/db.env
    networks:
      app_net:
        ipv4_address: 192.168.1.4

  master_db:
    image: mysql:5.7
    container_name: vote_master_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./slave_mysql/init/01_initial_db.sql:/docker-entrypoint-initdb.d/01_initial_db.sql
      - ./slave_mysql/master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      app_net:
        ipv4_address: 192.168.1.11

  slave_db:
    image: mysql:5.7
    container_name: vote_slave_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./slave_mysql/init/02_initial_db.sql:/docker-entrypoint-initdb.d/02_initial_db.sql
      - ./slave_mysql/slave.cnf:/etc/mysql/conf.d/slave.cnf
    networks:
      app_net:
        ipv4_address: 192.168.1.12

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          # gateway: 192.168.1.254

  # common_link:
  #   external: true

  # django_vote:
  #   driver: bridge
  #   external: true
