version: '3'
services:
  app:
    build: ./app
    container_name: vote_app
    restart: always
    tty: true
    expose:
      - 8000
    depends_on:
      - db
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
      - ./app/static/:/usr/src/app/static
    env_file:
      - ./envs/db.env
      - ./envs/app.env
      - .env
    networks:
      app_net:
        ipv4_address: 192.168.1.2
      # - django_vote

  nginx:
    image: nginx
    container_name: vote_nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/mime.types:/etc/nginx/mime.types"
      - "./app/static:/usr/src/app/static"
    depends_on:
      - app
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: 192.168.1.3
      # - django_vote

  db:
    # build: ./mysql
    image: mysql
    container_name: vote_db
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysitepass
      TZ: 'Asia/Tokyo'
    # volumes:
    #   - mysql_data:/var/lib/mysql
    #   - "./mysql/conf.d:/etc/mysql/conf.d"
    env_file:
      - ./envs/db.env
    networks:
      app_net:
        ipv4_address: 192.168.1.4


volumes:
  mysql_data:
    driver: local

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          # gateway: 192.168.1.254

  # common_link:
  #   external: true

  # django_vote:
  #   driver: bridge
  #   external: true
